openapi: "3.0.2"

info:
  title: Bright Events
  version: "1.0"

servers:
  - url: ...
    description: "Mock for url"

  - url: ...
    description: "Production server"

tags:
  - name: "M01: Authentication and Personal Profile"
  - name: "M02: User Search and User Profiles"
  - name: "M03: Events and Event-related Content"
  - name: "M04: Static Pages"
  - name: "M05: Administration Management"
  - name: "M06: Notifications"

# Permissions
# NAU - Non-authenticated User
# AU - Authenticated User
# AUO - User that organizes an event
# ADM - System administrator

paths:
  /api/notifications:
    get:
      operationId: R601
      summary: "R601: Retrieve notifications"
      description: "Retrieve user notifications. Access: AU"
      tags:
        - "M06: Notifications"
      responses:
        "401":
          description: "Unauthorized. User must be logged in"
        "403":
          description: "You don't have permissions to make this request"
        "200":
          description: "OK. Retrieve user notifications"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    date:
                      type: string
                      format: date-time
                    type:
                      type: string
                      enum: [
                        "Disabled event", 
                        "Cancelled event", 
                        "Join request", 
                        "Accepted request", 
                        "Declined request", 
                        "Invite", 
                        "Accepted invite", 
                        "Declined invite", 
                        "New comment", 
                        "New poll", 
                        "Poll closed"
                        ]
                    related_asset:
                      type: string
                      enum: ["Event", "Attendance request", "Poll", "Comment"]

  /api/notifications/{notificationId}:
    patch:
      operationId: R602
      summary: "R602: Edit notification"
      description: "Process the new notification information. Access: AU"
      tags:
        - "M06: Notifications"
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: integer
      
      requestBody:
        required: true
        application/x-www-form-urlencoded:
          schema:
            type: object
            parameters:
              is_seen:
                type: boolean
            required:
              - is_seen

      responses:
        "401":
          description: "Unauthorized. User must be logged in"
        "404":
          description: "Notification not found"
        "500":
          description: "Internal server error"
        "200":
          description: "Ok. Update notification"