openapi: '3.0.2'

info:
  title: Bright Events
  version: '1.0'

servers:
  - url: https://api.server.test/v1

tags:
  - name: 'M01: Authentication and Personal Profile'
  - name: 'M02: User Search and User Profiles'
  - name: 'M03: Events and Event-related Content'
  - name: 'M04: Static Pages'
  - name: 'M05: Administration Management'

# Permissions
# NAU - Non-authenticated User
# AU - Authenticated User
# AUO - User that organizes an event
# ADM - System administrator

paths:
  /:
    get:
      operationId: R401
      summary: 'R401: Home Page'
      description: 'Provide home page. Accessible by NAU, AU, AUO, ADM'
      tags:
        - 'M04: Static Pages'
      responses:
        '200':
          description: 'OK. Show home page (UI01)'
  
  /privacy-policy:
    get:
      operationId: R402
      summary: 'R402: Privacy Policy Page'
      description: 'Provide privacy policy page. Accessible by NAU, AU, AUO, ADM'
      tags:
        - 'M04: Static Pages'
      responses:
        '200':
          description: 'OK. Show privacy policy page (UI02)'

  /terms-and-conditions:
    get:
      operationId: R403
      summary: 'R403: Terms and Conditions Page'
      description: 'Provide terms and conditions page. Accessible by NAU, AU, AUO, ADM'
      tags:
        - 'M04: Static Pages'
      responses:
        '200':
          description: 'OK. Show terms and conditions page (UI03)'

  /faq:
    get:
      operationId: R404
      summary: 'R404: FAQ Page'
      description: 'Provide frequently asked questions page. Accessible by NAU, AU, AUO, ADM'
      tags:
        - 'M04: Static Pages'
      responses:
        '200':
          description: 'OK. Show FAQ page (UI04)'

  /about:
    get:
      operationId: R405
      summary: 'R405: About Page'
      description: 'Provide about page. Accessible by NAU, AU, AUO, ADM'
      tags:
        - 'M04: Static Pages'
      responses:
        '200':
          description: 'OK. Show about page (UI05)'

  /contact-us:
    get:
      operationId: R406
      summary: 'R406: Contact Us Page'
      description: 'Provide contact us page. Accessible by NAU, AU, AUO, ADM'
      tags:
        - 'M04: Static Pages'
      responses:
        '200':
          description: 'OK. Show contact us page (UI06)'
