openapi: "3.0.2"

info:
  title: Bright Events
  version: "1.0"

servers:
  - url: ...
    description: "Mock for url"

  - url: ...
    description: "Production server"

tags:
  - name: "M01: Authentication and Personal Profile"
  - name: "M02: User Search and User Profiles"
  - name: "M03: Events and Event-related Content"
  - name: "M04: Static Pages"
  - name: "M05: Administration Management"

# Permissions
# NAU - Non-authenticated User
# AU - Authenticated User
# AUO - User that organizes an event
# ADM - System administrator

paths:
  # M05: Administration Management

  /api/report/event:
    post:
      operationId: R500
      summary: "R500: Report event"
      description: "Report an event. Access: AU with event visibility"
      tags:
        - "M05: Administration Management"
      requestBody:
        description: "Report Form"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                motive:
                  type: string
                  enum:
                    [
                      "Sexual harassment",
                      "Violence or bodily harm",
                      "Nudity or explicit content",
                      "Hate speech",
                      "Other",
                    ]
                description:
                  type: string
                timestamp:
                  type: string
                  format: date-time
              required: [id, motive, description, timestamp]

      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to make this request."
        "404":
          description: "Id not found"
        "201":
          description: "OK. Event report created."

  /api/report/user:
    post:
      operationId: R501
      summary: "R501: Report user."
      description: "Report an user. Access: AU with user visibility"
      tags:
        - "M05: Administration Management"
      requestBody:
        description: "Id of the user to report"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                motive:
                  type: string
                  enum:
                    [
                      "Sexual harassment",
                      "Violence or bodily harm",
                      "Nudity or explicit content",
                      "Hate speech",
                      "Other",
                    ]
                description:
                  type: string
                timestamp:
                  type: string
                  format: date-time
              required: [id, motive, description, timestamp]

      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to make this request."
        "404":
          description: "Id not found"
        "201":
          description: "User report created."

  /api/report/message:
    post:
      operationId: R502
      summary: "R502: Report message."
      description: "Report a messge. Access: AU with message visibility"
      tags:
        - "M05: Administration Management"
      requestBody:
        description: "Id of the message to report"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                motive:
                  type: string
                  enum:
                    [
                      "Sexual harassment",
                      "Violence or bodily harm",
                      "Nudity or explicit content",
                      "Hate speech",
                      "Other",
                    ]
                description:
                  type: string
                timestamp:
                  type: string
                  format: date-time
              required: [id, motive, description, timestamp]

      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to make this request."
        "404":
          description: "Id not found"
        "201":
          description: "Message report created."

  /api/report:
    get:
      operationId: R503
      summary: "R503: Get reports"
      description: "Retrieve reports list"
      tags:
        - "M05: Administration Management"
      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to make this request."
        "200":
          description: "OK. Answer with reports list"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                      enum: [Event, User, Message]
                    motive:
                      type: string
                      enum:
                        [
                          "Sexual harassment",
                          "Violence or bodily harm",
                          "Nudity or explicit content",
                          "Hate speech",
                          "Other",
                        ]
                    creation:
                      type: string
                      format: date-time
                    reporter:
                      type: string
                    handler:
                      type: string

  /api/report/{reportId}:
    get:
      operationId: R504
      summary: "R504: Get report details"
      description: "Answer with report details"
      tags:
        - "M05: Administration Management"
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to make this request."
        "404":
          description: "Id not found"
        "200":
          description: "OK. Aswering with report details"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                    enum: [Event, User, Message]
                  motive:
                    type: string
                    enum:
                      [
                        "Sexual harassment",
                        "Violence or bodily harm",
                        "Nudity or explicit content",
                        "Hate speech",
                        "Other",
                      ]
                  creation:
                    type: string
                    format: date-time
                  reporter:
                    type: string
                  handler:
                    type: string
                  description:
                    type: string

    post:
      operationId: R505
      summary: "R505: Change report state"
      description: "Change report state, manipulating the resource availability. Access: ADM"
      tags:
        - "M05: Administration Management"
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: integer
        
      requestBody:
        description: "Action to take"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: string
              enum: ["Ignore", "Hide/Block", "Delete"]

      responses:
        "200":
          description: "OK. Action taken"
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to make this request."
        "404":
          description: "Id not found"
        "500":
          description: "Internal server failiure."

  /reports/:
    get:
      operationId: R506
      summary: "R506: Reports list page."
      description: "Show reports list page.  Accessible by ADM."
      tags:
        - "M05: Administration Management"
      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to access this page."
        "200":
          description: "OK. Show reports list page (UI07)"

  /reports/view:
    get:
      operationId: R507
      summary: "R507: Report details page."
      description: "Show report details page. Accessible by ADM."
      tags:
        - "M05: Administration Management"
      parameters:
        - name: reportId
          in: query
          description: Id of the report to view
          required: true
          schema:
            type: integer
      responses:
        "401":
          description: "No authentication found. Please login."
        "403":
          description: "You don't have permission to access this page."
        "404":
          description: "Id not found"
        "200":
          description: "OK. Show report details page (UI07)"
