openapi: '3.0.2'

info:
  title: Bright Events
  version: '1.0'

servers:
  - url: https://api.server.test/v1

tags:
  - name: 'M01: Authentication and Personal Profile'
  - name: 'M02: User Search and User Profiles'
  - name: 'M03: Events and Event-related Content'
  - name: 'M04: Static Pages'
  - name: 'M05: Administration Management'

# Permissions
# NAU - Non-authenticated User
# AU - Authenticated User
# AUO - User that organizes an event
# ADM - System administrator

paths:
  /sign-in:
    get:
      operationId: R101
      summary: 'R101: Sign-in Form'
      description: 'Provide sign-in form. Accessible by NAU'
      tags:
        - 'M01: Authentication and Personal Profile'
      responses:
        '200':
          description: 'OK. Show Sign-in form (UI09)'

    post:
      operationId: R102
      summary: 'R102: Sign-in Action'
      description: 'Processes the sign-in form. Accessible by NAU'
      tags:
        - 'M01: Authentication and Personal Profile'
      
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

      responses:
        '302':
          description: 'Post credentials processing redirect'
          headers:
            Location:
              description: 'Redirect path'
              schema:
                type: string
              examples:
                302Success:
                  description: 'Authentication succeeded. Redirecting to user profile.'
                  value: '/users/{id}'
                302Failure:
                  description: 'Authentication failed. Redirect to login form'
                  value: '/login' 

  /sign-out:
    post:
      operationId: R103
      summary: 'R103: Sign-out Action'
      description: 'Signs out the currently authenticated user. Accessible by AU, ADM'
      tags:
            - 'M01: Authentication and Personal Profile'
      responses:
        '302':
          description: 'Post sign-out redirect'
          headers:
            Location:
              description: 'Redirect path'
              schema:
                type: string
              examples:
                302Success:
                  description: 'Sign-out succeeded. Redirecting to home page'
                  value: '' # update when / is implemented