@startuml actors
skinparam monochrome true
skinparam backgroundColor transparent
skinparam actorStyle awesome

:Administrator: as admin
:Visitor: as V
:Non Authenticated User: as NAU
:Authenticated User: as AU
:Organizer: as AUO
:Attendee: as AUA


V <-- NAU
V <-- AU
AU <-- AUO
AU <-- AUA

@enduml